/**
 * BrickLink part id → English part name, generated by `npm run fetch-names`
 * (scripts/fetch-names.mjs, sourced from Rebrickable's parts database).
 * Not every id has a name — callers must handle the empty string.
 */
import names from '../data/part-names.json';

export function partName(partId: string): string {
  return (names as Record<string, string>)[partId] ?? '';
}
